server.port=${PORT:8080}
spring.application.name=route-optimizer-backend

# DATABASE
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/route_optimizer?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Teja@1234}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# CORS
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}